### ISSUE TITLE
Specificity (SP) becomes 0 during training.

### ISSUE THREAD

**Issue by Max-Well-Wang** [CN-zdy/MSU_Net#1]
Hello dear author, I like your paper very much. After I run the program on the EM Dataset, according to the parameters set in your code, the SP parameter will decrease as the training increases until it becomes 0, but the model can converge. The result is not satisfactory, I hope you can give me a hint, thank you very much!

**Comment by CN-zdy** [comment]
Hello, thank you for liking my paper. The epoch of each dataset is different. You can set the epoch to 20. If the problem has not been resolved, please continue to contact me.

**Comment by CN-zdy** [comment]
If u have no questions, i will close this on June 18th.
