### ISSUE TITLE
Initialization of network

### ISSUE THREAD

**Issue by pangda72** [CN-zdy/MSU_Net#11]
Hi，author,
I have some queries regarding your work? Colud you please give me a hint,thank you very much!

Initialization of network
There is a function 'init_weights' in network.py ,but I did not find any line using this function of the network initialization.
So could you please explain this to how? How does the code use this 'init_weights' function during training?

Looking forward to your reply.Thanks in advance.
Best.

**Comment by CN-zdy** [comment]
Although I added this code, I did not initialize the network.

You can add init_weights(self.unet) above or below self.unet.train() in slover.py

**Comment by pangda72** [comment]
> Although I added this code, I did not initialize the network.
> 
> You can add init_weights(self.unet) above or below self.unet.train() in slover.py

okay,thank you very much!
