### ISSUE TITLE
 five-fold Cross Validation

### ISSUE THREAD

**Issue by pangda72** [CN-zdy/MSU_Net#12]
Hi，CN-zdy,
I have some queries regarding your work? Colud you please give me a help,thank you very much!

Train using five-fold Cross Validation,then the parameters of five models are obtained,how to choose optimal model parameter to test the test sets.
In this code, the test set is also tested five times, I don't understand why it  needs to be tested five times.And getting five different results is choosing the best one or something else?

Looking forward to your reply.Thanks in advance.
Best.

**Comment by CN-zdy** [comment]
Hi, Pangda.
In my experiment, my final result was to take the average of the five tests

**Comment by pangda72** [comment]
> Hi, Pangda.
> In my experiment, my final result was to take the average of the five tests

Dear CN-zdy
I get it.Thank you so so much!
