### ISSUE TITLE
the problem about saving predicted masks

### ISSUE THREAD

**Issue by pangda72** [CN-zdy/MSU_Net#14]
Hi，CN-zdy,
I have some queries regarding your work? Colud you please give me a help,thank you very much!

In the 'solver.py',there is some codes:

                               torchvision.utils.save_image(images.data.cpu(),
							os.path.join(self.test_result_path,
							'%s_test_%d_image.png' % (self.model_type, epoch + 1)))
				torchvision.utils.save_image(SR.data.cpu(),
							os.path.join(self.test_result_path,
							'%s_test_%d_SR.png' % (self.model_type, epoch + 1)))
				torchvision.utils.save_image(GT.data.cpu(),
							os.path.join(self.test_result_path,
							'%s_test_%d_GT.png' % (self.model_type, epoch + 1)))

by run 'test.py',i got the predicted results. the  results floder shows:one epoch only save batchsize images?I don't know why ,could you give me a hand,it means a lot to me.

Looking forward to your reply.Thanks in advance.
Best.

**Comment by CN-zdy** [comment]
Hi, Pangda.
I don't understand your question, can you clarify it?

**Comment by pangda72** [comment]
> Hi, Pangda.
> I don't understand your question, can you clarify it?

I feel very sorry, i don't  clarify it.
What I want to ask you is：
1、I want to save a single image,but you already taught me In the previous question:
You can save a single image by adding image = SR[0, :, :, :] before saving.

2、My test set has 132 images,epoch is 20.I run 'test.py',there were only 20 SR in each of the five folders in my test set,not 132 SR.it is my understanding that all images(132 images)sholud be tested each epoch,the predicted results of each image should be saved,so there should be 132 SR in each of the five folders in the test set,but there were only 20 SR.I don't know why  ,Colud you please give me a help,thank you very much!

**Comment by CN-zdy** [comment]
Hi, Pangda.
This is limited by the test epochs.
You can use the traversal method to traverse the test set for prediction to get segmentation results.

**Comment by CN-zdy** [comment]
Hi, Pangda.
This is limited by the test epochs.
You can use the traversal method to traverse the test set for prediction to get segmentation results.

**Comment by pangda72** [comment]
> Hi, Pangda.
> This is limited by the test epochs.
> You can use the traversal method to traverse the test set for prediction to get segmentation results.

**Comment by CN-zdy** [comment]
Hi, Pangda.
If not solve this problem, you can send your contact information to my email (zhangdeyun2016@163.com). I'll help you solve this problem if I have time

**Comment by pangda72** [comment]
> Hi, Pangda.
> If not solve this problem, you can send your contact information to my email ([zhangdeyun2016@163.com](mailto:zhangdeyun2016@163.com)). I'll help you solve this problem if I have time
Dear CN-zdy
Thank you so  so much,So far I've been trying to solve this problem, but I'm not good at programming,So it never worked out .I'm glad to hear that.You have been grateful.

**Comment by CN-zdy** [comment]
Hi,Pangda.
The code has been sent to your email.
You can try it.

**Comment by pangda72** [comment]
> Hi,Pangda.
> The code has been sent to your email.
> You can try it.

Hi，CN-zdy
I have received the code.And i will try it.You've really done me a great favor. Thank you very much indeed.

**Comment by pangda72** [comment]
Hi，CN-zdy
I've tried to run the code you have  sent to me.The code can run successfully.
You helped me solve a problem that was very difficult for me .You're so nice and  help me a lot.
I appreciate your hard work.Thank you very much.
Best wishes.
