### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'beta1'

### ISSUE THREAD

**Issue by ghost** [CN-zdy/MSU_Net#3]
Hi, I am getting this error how can I solve this?
```
Namespace(batch_size=4, img_ch=1, k=5, lr=0.01, mode='train', model_path='./model/U_Net/第-1-折', model_type='U_Net', num_epochs=100, num_epochs_test=10, num_workers=0, output_ch=1, test_path='/data/Hammad/2_preprocessed_data/stage2/', test_result_path='./results/model/test_result/', train_result_path='./results/U_Net/train_result/第-1-折', train_valid_path='/data/Hammad/2_preprocessed_data/stage1/', val_result_path='./results/U_Net/val_result/第-1-折')
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    main(config)
  File "train.py", line 80, in main
    solver = Solver(config, train_loader, valid_loader, test_loader)
  File "/data/Hammad/MUNET/MSU_Net/solver.py", line 28, in __init__
    self.beta1 = config.beta1
AttributeError: 'Namespace' object has no attribute 'beta1'
```

**Comment by CN-zdy** [comment]
Sorry, some parameters are missing in train.py. Missing parameters have been added to train.py

**Comment by ghost** [comment]
Please update Readme How to train the network with-parameter,
One more error in solver.py line 217 and 225
self.augmentation_prob is not defined

wr.writerow(
						[self.model_type, t_TPR, t_FPR, t_PPV, t_JS, t_DC,t_SE, t_SP, epoch_loss, epoch + 1, self.num_epochs,
						self.augmentation_prob, learn_rate])

**Comment by CN-zdy** [comment]
Thank you for your interest in our work.
Since we deleted some of the content when uploading the code, there may be some minor issues. 
We will refine our work step by step in the next few days.

**Comment by CN-zdy** [comment]
Thank you for your interest in our work.
Since we deleted some of the content when uploading the code, there may be some minor issues. 
We will refine our work step by step in the next few days.
This issue has been fixed.

**Comment by CN-zdy** [comment]
If u have no questions, i will close this on July 23.

**Comment by ghost** [comment]
Will you please add other models to like :2U_Net/AttU_Net/CSAU_Net/R2AttU_Net/SRAttU_Net/RAttU_Net/DE_U_Net/DECSAU_Net/DER2U_Net/DE2AttU_Net/DER2AttU_Net/DE2R2AttU_Net'

**Comment by CN-zdy** [comment]
I am sorry about that.  We do not intend to expose these architectures.

You can try to build your own architecture based on U-Net.
