### ISSUE TITLE
How to take inference on test dataset and save predicted mask?

### ISSUE THREAD

**Issue by ghost** [CN-zdy/MSU_Net#6]
I have trained the model How can I use the model to predict the output and save it in another folder?

**Comment by CN-zdy** [comment]
Thank you for your interest in our work. 
You can get a prediction by running test.py. There is an annotated piece of code in the test section of slover.py that outputs the predicted split result.
This code has now been added to slover.py

**Comment by ghost** [comment]
Why do you multiple 0.5 for the test dataset?

**Comment by CN-zdy** [comment]
This is for unnormalization

**Comment by CN-zdy** [comment]
If u have no questions, i will close this on July 23.
