### ISSUE TITLE
requirements.txt file 

### ISSUE THREAD

**Issue by bushra-tayyaba** [CN-zdy/MSU_Net#7]
You have written to install requirements in the requirements.txt file but I do not found any

**Comment by CN-zdy** [comment]
Hi, I didn't write requirements.txt, You can install packages with code

**Comment by bushra-tayyaba** [comment]
Thank you very much for your response. 
can you please elaborate on the structure of the dataset you are using? Actually, I am not getting it

**Comment by CN-zdy** [comment]
Hi, You can find the the structure of the dataset in the Readme.
We place the original images and groundtruth in origin_images and groundtruth respectively in the data folder.
We partition the dataset in dataset.py, and the partition result is placed in data_*.

**Comment by bushra-tayyaba** [comment]
Thank you once again. Can I use this repository for any segmentation histology dataset other than yours? can you suggest what major changes we should commit?

**Comment by CN-zdy** [comment]
Our work is a universal framework that is not limited to the data set in the paper. You just need to arrange the files in the style given in the README. By the way, if the file is not in JPG/PNG format, you need to modify dataloader.py
