### ISSUE TITLE
My input size is 512x512,bit depth is 8,，but my output size is 518x260,bit depth is 24,I don't know what causes this problem.

### ISSUE THREAD

**Issue by pangda72** [CN-zdy/MSU_Net#9]
Hi CN-zdy
Thanks for your code.When I run '"test.py",I  got a problem,the size of  output results under the test folder is 512x260,and bit depth is 24,but my input size is 512x512,bit depth is 8.I don't know what causes this problem,Could you help me?
Looking forward to your reply.Thankes in advance.
Best.

**Comment by CN-zdy** [comment]
Hi, pangda.
The problem of image resizing can be solved by printing the size of features in the network.
The problem of depth changes is that the image channel is converted to 3 when saving the result. You can change the saving mode in slover.py.

**Comment by pangda72** [comment]
> Hi, pangda.
> The problem of image resizing can be solved by printing the size of features in the network.
> The problem of depth changes is that the image channel is converted to 3 when saving the result. You can change the saving mode in slover.py.

CN-zdy,Thank you for your advice.I solved the bit depth problem by your help.But I'm a little confused about the first question.On the first question, there may be something wrong with my expression. I don't know why the output is saved to show two results on one image .For example:the batchsize of train and validation is 4,Save results show four output results on a single image.the batchsize of test is 2,Save results display  two output results on a single image.My idea is that one image shows one picture, and I don't know why it shows that way . Could you help me ?Thanks very much!
![U_Net_test_1_GT](https://user-images.githubusercontent.com/74399643/132841528-67ed5a5d-c3d3-4364-bbbf-c0ef13111e87.png)

![U_Net_train_59_GT](https://user-images.githubusercontent.com/74399643/132841245-5d4881bc-cd72-42ee-a77f-bc0418a17c68.png)

**Comment by CN-zdy** [comment]
This is because the saved files directly save batches. 
You can save a single image by adding image = SR[0, :, :, :] before saving.

**Comment by pangda72** [comment]
> This is because the saved files directly save batches.
> You can save a single image by adding image = SR[0, :, :, :] before saving.
Dear CN-zdy,
Thanks to your help, I solved this question just now.
Thank you very much,You have been grateful!
Best.
